### PR TITLE
Rename functions to something more verb-like

### PR DESCRIPTION
**Pull request by AntoniosProvidakis**
I think the API is better when functions use verb-like names.

### CODE REVIEW

**Comment by aishek** [comment]
Antonios, thanks for your contribution! I also prefer verb-like names. I'll merge it, but will release a new version later, when more notable changes came.

Could you update `CHANGELOG.md` with `breaking` label? I believe someone could already rely on the current API. So it will be fine to notify them somehow.

**Comment by AntoniosProvidakis** [comment]
@aishek But, the only public API you expose, is the  **axiosRateLimit** function, not the **AxiosRateLimit** (note the capital "A"). All the changes to AxiosRateLimit are internal.

I think there is no need to notify any user of the package.

What do you think?

**Comment by aishek** [comment]
Oh, I've missed it. You're right.

**Comment by aishek** [comment]
@AntoniosProvidakis just merged all requests and published version `1.0.1`. Huge thanks for the contribution!

**Pull request merged**
